### ISSUE TITLE
Hello, I run your code without dynamically adding or deleting source.

### ISSUE THREAD

**Issue by aitangbodan** [vinodbukya6/Runtime-Source-Add-Delete-DeepStream#2]
Running deepstream code does not dynamically add or remove sources.

**Comment by vinodbukya6** [comment]
Hi, 
After my implementation there are few updates were added. Please check here: https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/tree/master/apps/runtime_source_add_delete

Let me know if you face any challenges. Happy to help!!!

**Comment by aitangbodan** [comment]
Thanks for your reply, Nvidia 's code only sets the time delay to add or delete streams, but cannot add and delete streams in real time. I made a change to the code, also did not solve, but the threads are parallel, and can not dynamically add or delete streams.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "BUKYA ***@***.***&gt;; 
发送时间: 2022年10月26日(星期三) 中午11:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [vinodbukya6/Runtime-Source-Add-Delete-DeepStream] Hello, I run your code without dynamically adding or deleting source. (Issue #2)






Hi,
After my implementation there are few updates were added. Please check here:https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/tree/master/apps/runtime_source_add_delete

Let me know if you face any challenges. Happy to help!!!

**Comment by vinodbukya6** [comment]
Here is the working demo video of source add or delete: https://drive.google.com/file/d/1UCc_UQuzT8bNkNyK3nS8-2vWYcaaPXL-/view?usp=sharing

Are you looking for this kind of pipeline?

**Comment by aitangbodan** [comment]
&nbsp;Thank you for your reply, but you sent me the video I can not open, I am sorry to delay your time, I study again, thank you again warm reply !




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "BUKYA ***@***.***&gt;; 
发送时间: 2022年10月26日(星期三) 中午11:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [vinodbukya6/Runtime-Source-Add-Delete-DeepStream] Hello, I run your code without dynamically adding or deleting source. (Issue #2)






Here is the working demo video of source add and delete:https://drive.google.com/file/d/1UCc_UQuzT8bNkNyK3nS8-2vWYcaaPXL-/view?usp=sharing

Are you looking for this kind of process/flow?

**Comment by vinodbukya6** [comment]
Hi,
Can you please download the video and watch?

**Comment by aitangbodan** [comment]
I tried, but I couldn't. That's fine. Thank you for your reply.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "BUKYA ***@***.***&gt;; 
发送时间: 2022年10月26日(星期三) 晚上6:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [vinodbukya6/Runtime-Source-Add-Delete-DeepStream] Hello, I run your code without dynamically adding or deleting source. (Issue #2)





 
Hi,
 Can you please download the video and watch?

**Comment by vinodbukya6** [comment]
Please share your Mail ID will send the video.

**Comment by aitangbodan** [comment]
My email is ***@***.*** Thank you for your kindness.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "BUKYA ***@***.***&gt;; 
发送时间: 2022年10月26日(星期三) 晚上6:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [vinodbukya6/Runtime-Source-Add-Delete-DeepStream] Hello, I run your code without dynamically adding or deleting source. (Issue #2)





 
Please share your Mail ID will send the video.

**Comment by vinodbukya6** [comment]
Hi @aitangbodan 
Can you ping me at bukyavinnunaik@gmail.com ?

**Comment by aitangbodan** [comment]
Thank you for your reply, I can 't get your email address, nothing, don 't care, later have questions can contact each other.
&nbsp;


♂逍遥梦♀
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "BUKYA ***@***.***&gt;; 
发送时间: 2022年10月31日(星期一) 晚上8:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [vinodbukya6/Runtime-Source-Add-Delete-DeepStream] Hello, I run your code without dynamically adding or deleting source. (Issue #2)





 
Hi @aitangbodan
 Can you ping me at ***@***.*** ?
 ***@***.***/

**Comment by vinodbukya6** [comment]
Cool
